CREATE OR REPLACE FUNCTION fn_detalhes_venda(p_cod_venda INT)
RETURNS TABLE (id_da_venda INT, data_venda DATE, valor_total_venda FLOAT, nome_cliente VARCHAR, nome_funcionario VARCHAR, nome_carro VARCHAR, marca_carro VARCHAR, quantidade_itens INT, preco_unitario FLOAT, subtotal FLOAT) AS $$
DECLARE
	v_venda_existe INT;
BEGIN
	SELECT COUNT(*) INTO v_venda_existe FROM VENDA WHERE VENDA.COD_VENDA = p_cod_venda;
	IF v_venda_existe = 0 THEN
		RAISE EXCEPTION 'Venda com código % não encontrada.', p_cod_venda;
	END IF;
	RETURN QUERY
	SELECT V.COD_VENDA, V.DT_VENDA, V.VALOR_TOTAL, CL.NOME, F.NOME, C.NOME, M.NOME, IV.QTD_DE_ITENS, C.PRECO, (IV.QTD_DE_ITENS * C.PRECO)::FLOAT
	FROM VENDA AS V
	JOIN CLIENTE AS CL ON V.COD_CLIENTE = CL.COD_CLIENTE
	JOIN FUNCIONARIO AS F ON V.COD_FUNCIONARIO = F.COD_FUNCIONARIO
	JOIN ITEM_VENDA AS IV ON V.COD_VENDA = IV.COD_VENDA
	JOIN LOJA_CARRO AS LC ON IV.COD_LOJA_CARRO = LC.COD_LOJA_CARRO
	JOIN CARRO AS C ON LC.COD_CARRO = C.COD_CARRO
	JOIN MARCA AS M ON C.COD_MARCA = M.COD_MARCA
	WHERE V.COD_VENDA = p_cod_venda;
END;
$$ LANGUAGE plpgsql;