CREATE OR REPLACE FUNCTION fn_funcionario_campeao_de_vendas()
RETURNS TABLE (nome_funcionario VARCHAR, total_vendido_no_mes FLOAT) AS $$
BEGIN
	RETURN QUERY
	SELECT F.NOME, F.QTD_VENDIDA_NO_MES
	FROM FUNCIONARIO AS F
	WHERE F.QTD_VENDIDA_NO_MES = (SELECT MAX(QTD_VENDIDA_NO_MES) FROM FUNCIONARIO WHERE QTD_VENDIDA_NO_MES > 0);
END;
$$ LANGUAGE plpgsql;