CREATE OR REPLACE FUNCTION fn_total_vendido_por_loja()
RETURNS TABLE (nome_da_loja VARCHAR, valor_total_vendido FLOAT) AS $$
BEGIN
    RETURN QUERY
    SELECT L.NOME, COALESCE(SUM(V.VALOR_TOTAL), 0) AS total_vendido
    FROM LOJA AS L
    LEFT JOIN FUNCIONARIO AS F ON L.COD_LOJA = F.COD_LOJA
    LEFT JOIN VENDA AS V ON F.COD_FUNCIONARIO = V.COD_FUNCIONARIO
    GROUP BY L.NOME
    ORDER BY total_vendido DESC;
END;
$$ LANGUAGE plpgsql;