CREATE OR REPLACE FUNCTION checa_meta()
RETURNS TRIGGER AS $$
DECLARE
total FLOAT;
meta FLOAT;
BEGIN
SELECT QTD_VENDIDA_NO_MES, META_MENSAL INTO total, meta
FROM FUNCIONARIO
WHERE COD_FUNCIONARIO = NEW.COD_FUNCIONARIO;

IF (total + NEW.VALOR_TOTAL) >= meta THEN
RAISE NOTICE 'Funcionário atingiu ou ultrapassou a meta mensal!';
END IF;

RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_checa_meta
BEFORE INSERT ON VENDA
FOR EACH ROW EXECUTE FUNCTION checa_meta();
