CREATE OR REPLACE FUNCTION fn_validar_funcionario_cliente() RETURNS TRIGGER AS $$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM FUNCIONARIO WHERE COD_FUNCIONARIO = NEW.COD_FUNCIONARIO) THEN
		RAISE EXCEPTION 'Funcionário com código % não existe.', NEW.COD_FUNCIONARIO;
	END IF;
	IF NOT EXISTS (SELECT 1 FROM CLIENTE WHERE COD_CLIENTE = NEW.COD_CLIENTE) THEN
		RAISE EXCEPTION 'Cliente com código % não existe.', NEW.COD_CLIENTE;
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_validar_funcionario_cliente BEFORE INSERT OR UPDATE ON VENDA
FOR EACH ROW EXECUTE FUNCTION fn_validar_funcionario_cliente();