CREATE OR REPLACE FUNCTION total_da_venda() RETURNS TRIGGER AS 
$$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE VENDA 
        SET VALOR_TOTAL = (
            SELECT SUM(IV.QTD_DE_ITENS * C.PRECO)
            FROM ITEM_VENDA AS IV
            JOIN LOJA_CARRO AS LC ON IV.COD_LOJA_CARRO = LC.COD_LOJA_CARRO
            JOIN CARRO AS C ON LC.COD_CARRO = C.COD_CARRO
            WHERE IV.COD_VENDA = NEW.COD_VENDA
        )
        WHERE COD_VENDA = NEW.COD_VENDA;

        UPDATE CARRO 
        SET QTD_EM_ESTOQUE = QTD_EM_ESTOQUE - NEW.QTD_DE_ITENS
        WHERE COD_CARRO = (
            SELECT LC.COD_CARRO
            FROM LOJA_CARRO AS LC
            WHERE LC.COD_LOJA_CARRO = NEW.COD_LOJA_CARRO
        );

    ELSIF TG_OP = 'UPDATE' THEN
        UPDATE VENDA 
        SET VALOR_TOTAL = (
            SELECT SUM(IV.QTD_DE_ITENS * C.PRECO)
            FROM ITEM_VENDA AS IV
            JOIN LOJA_CARRO AS LC ON IV.COD_LOJA_CARRO = LC.COD_LOJA_CARRO
            JOIN CARRO AS C ON LC.COD_CARRO = C.COD_CARRO
            WHERE IV.COD_VENDA = NEW.COD_VENDA
        )
        WHERE COD_VENDA = NEW.COD_VENDA;

        UPDATE CARRO
        SET QTD_EM_ESTOQUE = QTD_EM_ESTOQUE + OLD.QTD_DE_ITENS
        WHERE COD_CARRO = (
            SELECT LC.COD_CARRO
            FROM LOJA_CARRO AS LC
            WHERE LC.COD_LOJA_CARRO = OLD.COD_LOJA_CARRO
        );

        UPDATE CARRO
        SET QTD_EM_ESTOQUE = QTD_EM_ESTOQUE - NEW.QTD_DE_ITENS
        WHERE COD_CARRO = (
            SELECT LC.COD_CARRO
            FROM LOJA_CARRO AS LC
            WHERE LC.COD_LOJA_CARRO = NEW.COD_LOJA_CARRO
        );

    ELSIF TG_OP = 'DELETE' THEN
        UPDATE VENDA 
        SET VALOR_TOTAL = (
            SELECT COALESCE(SUM(IV.QTD_DE_ITENS * C.PRECO), 0)
            FROM ITEM_VENDA AS IV
            JOIN LOJA_CARRO AS LC ON IV.COD_LOJA_CARRO = LC.COD_LOJA_CARRO
            JOIN CARRO AS C ON LC.COD_CARRO = C.COD_CARRO
            WHERE IV.COD_VENDA = OLD.COD_VENDA
        )
        WHERE COD_VENDA = OLD.COD_VENDA;

        UPDATE CARRO 
        SET QTD_EM_ESTOQUE = QTD_EM_ESTOQUE + OLD.QTD_DE_ITENS
        WHERE COD_CARRO = (
            SELECT LC.COD_CARRO
            FROM LOJA_CARRO AS LC
            WHERE LC.COD_LOJA_CARRO = OLD.COD_LOJA_CARRO
        );
    END IF;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER total_da_venda_tr 
AFTER INSERT OR UPDATE OR DELETE ON ITEM_VENDA
FOR EACH ROW EXECUTE FUNCTION total_da_venda();

