-- Tabela de Itens de Venda (referência a VENDA e LOJA_CARRO)
CREATE TABLE ITEM_VENDA (
    COD_ITEM_VENDA INT PRIMARY KEY,
    COD_VENDA INT,
    COD_LOJA_CARRO INT,
    QTD_DE_ITENS INT,
    FOREIGN KEY (COD_VENDA) REFERENCES VENDA(COD_VENDA)
);