CREATE OR REPLACE FUNCTION fn_checa_meta() RETURNS TRIGGER AS $$
DECLARE
	total FLOAT;
	meta FLOAT;
BEGIN
	SELECT QTD_VENDIDA_NO_MES, META_MENSAL INTO total, meta FROM FUNCIONARIO WHERE COD_FUNCIONARIO = NEW.COD_FUNCIONARIO;
	IF (total + NEW.VALOR_TOTAL) >= meta THEN
		RAISE NOTICE 'Parabéns! O funcionário com código % atingiu ou ultrapassou a meta mensal!', NEW.COD_FUNCIONARIO;
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tg_checa_meta BEFORE INSERT OR UPDATE ON VENDA
FOR EACH ROW EXECUTE FUNCTION fn_checa_meta();