CREATE TABLE FUNCIONARIO (
	COD_FUNCIONARIO INT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	SALARIO FLOAT NOT NULL,
	META_MENSAL FLOAT NOT NULL,
	QTD_VENDIDA_NO_MES FLOAT NOT NULL,
	COD_LOJA INT NOT NULL REFERENCES LOJA(COD_LOJA)
);
