CREATE TABLE ITEM_VENDA (
	COD_ITEM_VENDA INT PRIMARY KEY,
	COD_VENDA INT NOT NULL REFERENCES VENDA(COD_VENDA),
	COD_LOJA_CARRO INT NOT NULL REFERENCES LOJA_CARRO(COD_LOJA_CARRO),
	QTD_DE_ITENS INT NOT NULL
);