CREATE TABLE VENDA (
	COD_VENDA INT PRIMARY KEY,
	COD_FUNCIONARIO INT NOT NULL REFERENCES FUNCIONARIO(COD_FUNCIONARIO),
	COD_CLIENTE INT NOT NULL REFERENCES CLIENTE(COD_CLIENTE),
	VALOR_TOTAL FLOAT NOT NULL,
	DT_VENDA DATE NOT NULL
);
