-- Tabela de Vendas (referência a FUNCIONARIO e CLIENTE)
CREATE TABLE VENDA (
    COD_VENDA INT PRIMARY KEY,
    COD_FUNCIONARIO INT,
    COD_CLIENTE INT,
    VALOR_TOTAL FLOAT,
    DT_VENDA DATE,
    FOREIGN KEY (COD_FUNCIONARIO) REFERENCES FUNCIONARIO(COD_FUNCIONARIO),
    FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);