-- Tabela de associação entre Loja e Carro (referência a LOJA e CARRO, usada por ITEM_VENDA)
CREATE TABLE LOJA_CARRO (
	COD_LOJA_CARRO INT PRIMARY KEY,
	COD_LOJA INT, 
	COD_CARRO INT,
	FOREIGN KEY (COD_LOJA) REFERENCES LOJA(COD_LOJA),
	FOREIGN KEY (COD_CARRO) REFERENCES CARRO(COD_CARRO)
);

INSERT INTO LOJA_CARRO 
VALUES
(1,1,1),
(2,2,2),
(3,3,3);