CREATE OR REPLACE FUNCTION fn_historico_compras_cliente(p_cod_cliente INT)
RETURNS TABLE (data_da_compra DATE, id_venda INT, nome_carro VARCHAR, marca_carro VARCHAR, quantidade INT, preco_unitario FLOAT, subtotal FLOAT) AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM CLIENTE WHERE COD_CLIENTE = p_cod_cliente) THEN
        RAISE NOTICE 'AVISO: O cliente com o código % não foi encontrado.', p_cod_cliente;
        RETURN;
    END IF;
    RETURN QUERY
    SELECT V.DT_VENDA, V.COD_VENDA, C.NOME, M.NOME, IV.QTD_DE_ITENS, C.PRECO, (IV.QTD_DE_ITENS * C.PRECO)::FLOAT
    FROM VENDA AS V
    JOIN ITEM_VENDA AS IV ON V.COD_VENDA = IV.COD_VENDA
    JOIN LOJA_CARRO AS LC ON IV.COD_LOJA_CARRO = LC.COD_LOJA_CARRO
    JOIN CARRO AS C ON LC.COD_CARRO = C.COD_CARRO
    JOIN MARCA AS M ON C.COD_MARCA = M.COD_MARCA
    WHERE V.COD_CLIENTE = p_cod_cliente
    ORDER BY V.DT_VENDA DESC, V.COD_VENDA;
END;
$$ LANGUAGE plpgsql;