CREATE TABLE CARRO (
	COD_CARRO INT PRIMARY KEY,
	COD_COR INT NOT NULL REFERENCES COR(COD_COR),
	COD_MARCA INT NOT NULL REFERENCES MARCA(COD_MARCA),
	COD_TIPO INT NOT NULL REFERENCES TIPO(COD_TIPO),
	NOME VARCHAR(20) NOT NULL,
	PRECO FLOAT NOT NULL,
	ANO VARCHAR(20) NOT NULL,
	QTD_EM_ESTOQUE INT NOT NULL
);